### ISSUE TITLE
Offline Message from Jeffrey Grethe: Might want a special place for part-of h...

### ISSUE THREAD

**Issue by SciCrunch-Synapse** [SciCrunch/NIF-Ontology#107]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#16539](https://scicrunch.zendesk.com/agent/tickets/16539)
**Priority:** N/A
**Group:** Support
**Requester:** jgrethe@ncmir.ucsd.edu
**Organization:** N/A
**Assignee:** N/A

**Original ticket description:**

<blockquote><div class="zd-comment">
<p dir="auto">From: Jeffrey Grethe &lt;<a href="mailto:jgrethe@ncmir.ucsd.edu" rel="noreferrer">jgrethe@ncmir.ucsd.edu</a>&gt;
<br>Phone: 
<br>Location: La Jolla, United States
<br>URL: <a href="https://scicrunch.org/scicrunch/about/term/ilx/ilx_0105021?searchTerm=hippocampus" rel="nofollow noreferrer" target="_blank">https://scicrunch.org/scicrunch/about/term/ilx/ilx_0105021?searchTerm=hippocampus</a>
<br>Department: </p>

<p dir="auto">Might want a special place for part-of hierarchy as well as Children</p>

<p dir="auto">----
<br>Zopim
<br><a href="https://www.zopim.com" rel="nofollow noreferrer" target="_blank">https://www.zopim.com</a></p>
</div></blockquote>

**Comment by tgbugs** [comment]
@yul129 this needs to be sorted into in the SciCrunch-UI tracker so closing here.
