### ISSUE TITLE
version iris

### ISSUE THREAD

**Issue by tgbugs** [SciCrunch/NIF-Ontology#119]
Set up resolver for version iris so that we have a releases file that maps git commit hashes to ontology filenames. The ideal solution here would be to have `http://ontology.neuinfo.org/NIF/ttl/NIF-Somefile/$(date +%s)/NIF-Somefile.ttl` -> the latest commit (affecting that file?) that occurred prior to `$(date +%s)`, as a simple way to implement maximally granular identifier versioning on a per file basis (as per suggestions from the RDA identifier versioning group).

**Comment by tgbugs** [comment]
In addition we need to switch over to importing external ontologies by their version iri (where supported) and have a way to automatically check for new versions.

**Comment by tgbugs** [comment]
It is not simple to get this to work and to include a valid owl:versionIRI in the file itself.
1. The resolver needs to convert epoch time to the commit hash that has the supremum of all timestamps less than the epoch time for that file. See below for the sanity checks.
2. Backdate the commit timestamps for commits that modify ontology files to 1 tick less than the smallest versionIRI epoch given that the checks below are passed.

Full description of checks for step 1:  At the resolved commit the file in question should have the supremum epoch time for all owl:versionIRIs for that file less than the epoch time given to the resolver, and that the commit epoch should be less than the versionIRI epoch.

Full description of checks for step 2: At commit time the owl:versionIRI must be set such that it is greater than commit timestamp but less than the timestamp of the next commit. The ideal solution would simply be to use a commit hook to set everything up so that the owl:versionIRI is set exactly 1 tick after the commit timestamp. Better yet the commit timestamp could be backdated to 1 tick prior to the smallest owl:versionIRI among all ontology files being committed with a check to make sure that that timestamp was not less than that of the supremum of all timestamps associated with the prior commit (guaranteeing that its timestamp is also greater than that of the prior commit if that commit included ontology files, otherwise we need to check that the current commit timestamp is greater than the previous commit). Another way to implement the check would be to make sure that the minimum versionIRI epoch for any new commit was at least 2 ticks greater than maximum of all current versionIRI epochs for all files in the repo (checking only against the prior commit might work, but better to check against everything to prevent weird bugs).

@cmungall do you foresee any pitfalls with employing this scheme for our version iris?

**Comment by tgbugs** [comment]
By a considerable stroke of good fortune GitHub already has this functionality implemented!

Using `date -Ins --date "@${epoch}"` produces a timestamp that can put put directly into github on a per file basis. For example.
```bash
#!/usr/bin/env sh
user=SciCrunch
repo=NIF-Ontology
branch=uri-switch
filepath=ttl/generated/doid-dead.ttl
epoch=1507847902
date_expr=@{$(date -Ins --date "@${epoch}")}
echo https://github.com/${user}/${repo}/blob/${branch}${date_expr}/${filepath}?raw=true
```
produces
`https://github.com/SciCrunch/NIF-Ontology/blob/uri-switch@{2017-10-12T15:38:22,854639603-07:00}/ttl/generated/doid-dead.ttl will return doid-dead.ttl?raw=true` and returns our file exactly as we want.

**Comment by tgbugs** [comment]
Since these 'versions' are not really 'releases' in the sense that they are used in the obo world, the scheme I have set up for the version iris is: `http://ontology.neuinfo.org/NIF/path/to/file/version/${epoch}/file.ttl`. These versions will work for any time point where the file in question was in the tree and are far more granular than will ever be meaningful in terms of real changes to any of the ontology files. In order for these to be useful I need to implement step 2 so that we can reference concrete and meaningful timepoints via `owl:versionIRI`.

**Comment by tgbugs** [comment]
The current implementation which uses pull requests instead of rebasing does not work because github knows that it was on another branch. Sigh. Will look into ways we could get this to work.

**Comment by cmungall** [comment]
Our protocol is typically:

 * run `make release` which has robot stamp the release ontology with a data-based versionIRI
 * commit and push
 * use the github release mechanism, and have the /releases/ purl redirect to the tag in github

https://github.com/INCATools/ontology-starter-kit/blob/master/template/src/ontology/README-editors.md#release-manager-notes

**Comment by tgbugs** [comment]
Could use https://api.github.com/repos/SciCrunch/NIF-Ontology/commits?committer_date<:1516405645 but then it could not be a simple redirect and would require processing (author_date may be correct?). Also https://github.com/tgbugs/timestamp-test.

**Comment by tgbugs** [comment]
`curl -H "Accept: application/vnd.github.cloak-preview" https://api.github.com/search/commits?q=repo:SciCrunch/NIF-Ontology+author-date:$(date -Is --date "@$(cat ttl/nif.ttl | grep versionIRI | grep [0-9]+ -oE)")` would work but only for exact dates and only for master. It maybe be possible to use <= on the date but not 100% sure.

**Comment by tgbugs** [comment]
Closed via https://github.com/tgbugs/pyontutils/commit/f934f60fb8f783b51e891b230ec3452c271aae3e and https://github.com/SciCrunch/NIF-Ontology/commit/12fe74cdecd6a83fc25756b8ffee6e85e1b1f960.
