### ISSUE TITLE
align NLXMOL:20090512 and PR:000015188

### ISSUE THREAD

**Issue by tgbugs** [SciCrunch/NIF-Ontology#131]
Probably via interlex existing ids.

**Comment by tmsincomb** [comment]
When you say align, do you mean add PR:000015188 or replace NLXMOL:20090512 with PR:000015188?

**Comment by jgrethe** [comment]
We should probably have PR as the preferred CURIE? We would keep NLXMOL since it has been used in the past...

**Comment by tgbugs** [comment]
Add. At this point with existing IDs we are pretty much never going to 'replace.' I still need to review PR and figure out how to import the new version before we can consider deprecating the nif identifiers, so for now I would not set PR as default.

**Comment by tmsincomb** [comment]
Also, you had assigned me just one specific mapping of NLXMOL:id to PR:id.
Did you want me to add all the equivalent mapping PR to NLXMOL? If so,
which ttl file should I use?

**Comment by tgbugs** [comment]
There is this file: https://github.com/SciCrunch/NIF-Ontology/blob/master/ttl/NIF-PRO-Bridge.ttl that could be used, but since those are equivalence declarations we need to figure out exactly how to handle those cases for existing ids, because existing ids are not all owl:equivalentClass to each other.

**Comment by tgbugs** [comment]
Done for now, we will address the bridge file when we synchronize the ontology back to interlex.
