### ISSUE TITLE
mbaslim.ttl and hbaslim.ttl missing in parcellation.ttl

### ISSUE THREAD

**Issue by MFSY** [SciCrunch/NIF-Ontology#134]
Hi,

The two following parcellation schemes are no longer (starting at v3.1) imported in [parcellation.ttl](https://github.com/SciCrunch/NIF-Ontology/blob/v3.1/ttl/generated/parcellation.ttl):

*mbaslim.ttl
*hbaslim.ttl

Is there any reason why they were removed ? I note that they were still imported in v3.0.

**Comment by MFSY** [comment]
Okay I see. Thanks. 
Missed the [parcellation-artifacts.ttl](https://github.com/SciCrunch/NIF-Ontology/blob/master/ttl/generated/parcellation-artifacts.ttl).

**Comment by tgbugs** [comment]
Yep. There is also [parcellation-core.ttl](https://github.com/SciCrunch/NIF-Ontology/blob/master/ttl/generated/parcellation-core.ttl) but it is mostly empty at the moment since I haven't populated it with the backend annotation and object property definitions yet.
