### ISSUE TITLE
moving Community to pyontutils

### ISSUE THREAD

**Issue by tgbugs** [SciCrunch/NIF-Ontology#135]
@jgrethe I am going to move the Community folder to https://github.com/tgbugs/pyontutils/tree/master/development which is the structure I already had in place for this. If there is an issue with that please let me know.

**Comment by jgrethe** [comment]
Hi Tom,
We need to make sure we have very visible documentation in the ontology repo then.  If someone wants to contribute to the ontology - the natural place they would go is the ontology repo...

> On Mar 24, 2018, at 02:03, Tom Gillespie <notifications@github.com> wrote:
> 
> @jgrethe <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jgrethe&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=VoBnXVyFWlbGZNrES22a2h0PqI4m1kGEUyTwLwBBYIQ&m=01OG0WoFpis5SCw7WO6lIGr6TfQdChC1A3fZkEP6Kws&s=z7vs8CK6sTydG5F-Go9eWpFr5G4akxOzOs3TkhVYzL0&e=> I am going to move the Community folder to https://github.com/tgbugs/pyontutils/tree/master/development <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tgbugs_pyontutils_tree_master_development&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=VoBnXVyFWlbGZNrES22a2h0PqI4m1kGEUyTwLwBBYIQ&m=01OG0WoFpis5SCw7WO6lIGr6TfQdChC1A3fZkEP6Kws&s=E6n0GwgsELMLyL5ymPffZ_CPP8nGpXXI9NTQdEUs9Ho&e=> which is the structure I already had in place for this. If there is an issue with that please let me know.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_SciCrunch_NIF-2DOntology_issues_135&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=VoBnXVyFWlbGZNrES22a2h0PqI4m1kGEUyTwLwBBYIQ&m=01OG0WoFpis5SCw7WO6lIGr6TfQdChC1A3fZkEP6Kws&s=wVyuloIVTYpilB6JK0e4oWfUtVKJOTXE3foFVbrc5cA&e=>, or mute the thread <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABjyZZ7wkepqZhO7QtgCKTIVK8UF7tbVks5thgvWgaJpZM4S5qVb&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=VoBnXVyFWlbGZNrES22a2h0PqI4m1kGEUyTwLwBBYIQ&m=01OG0WoFpis5SCw7WO6lIGr6TfQdChC1A3fZkEP6Kws&s=aMnZuUHRKfjNcL_G5TfIHX8xVnwt2VhHxkBJKTi0c4A&e=>.
> 

_________________________________________________________________

Jeffrey S. Grethe, Ph.D.                                              email: jgrethe@ncmir.ucsd.edu <mailto:jgrethe@ncmir.ucsd.edu>    
University of California, San Diego
9500 Gilman Drive, M/C 0608
La Jolla, CA 92093-0608

work: (858) 822-0703 (
fax: (858) 246-0644

UCSD Profile: http://profiles.ucsd.edu/jeffrey.grethe <http://profiles.ucsd.edu/jeffrey.grethe>
ORCID: http://orcid.org/0000-0001-5212-7052 <http://crbs.ucsd.edu/>
LinkedIn: http://www.linkedin.com/in/jgrethe <http://www.linkedin.com/in/jgrethe>

This e-mail/fax message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail/fax and destroy all copies of the original message.

**Comment by tgbugs** [comment]
Added https://github.com/SciCrunch/NIF-Ontology#non-ontology-files.
