### ISSUE TITLE
pka, pkc, mapk synonym issues

### ISSUE THREAD

**Issue by tgbugs** [SciCrunch/NIF-Ontology#17]
I think this is probably an issue in GO but PKA, PKC, and MAPK are all listed as synonyms on GO:0004674 "protein serine/threonine kinase activity" which is incorrect and their actual protein entities (families?) don't have them listed as abbrevs or syns. Leads to nasty results.

**Comment by memartone** [comment]
I looked it up in GO and I don’t see these as synonyms.  They really couldn’t be as one is a molecule and one is a molecular function.  Could this be coming from SciGraph?

**Comment by tgbugs** [comment]
The issue appears in scigraph, see [here](http://matrix.neuinfo.org:9000/scigraph/vocabulary/search/pkc?searchSynonyms=true&limit=40&searchAbbreviations=false&searchAcronyms=false). I'm trying to figure out which ontology that is being pulled in from.

**Comment by tgbugs** [comment]
Looks like these are coming from our (out of date) local copy of go.owl located here: http://ontology.neuinfo.org/NIF/BiomaterialEntities/go.owl

In the github version this issue has been fixed because I now import the latest version of go, but I haven't switched the ftp version over yet.
