### ISSUE TITLE
curies sometimes have # in them

### ISSUE THREAD

**Issue by tgbugs** [SciCrunch/NIF-Ontology#18]
http://matrix.neuinfo.org:9000/scigraph/vocabulary/term/METHYLPHENIDATE

produces a curie of "OBO:chebi.owl#CHEBI_6887" from iri
"http://purl.obolibrary.org/obo/chebi.owl#CHEBI_6887"
this is undesirable since it means we have to do substitution from # -> %23 for the curie to work in another query

**Comment by jgrethe** [comment]
Shouldn’t this default to CHEBI_6887 then? OBO is a library - its constituents should be what is listed…

> On Oct 2, 2015, at 4:25 PM, Tom Gillespie <notifications@github.com> wrote:
> 
> http://matrix.neuinfo.org:9000/scigraph/vocabulary/term/METHYLPHENIDATE <http://matrix.neuinfo.org:9000/scigraph/vocabulary/term/METHYLPHENIDATE>
> produces a curie of "OBO:chebi.owl#CHEBI_6887" from iri
> "http://purl.obolibrary.org/obo/chebi.owl#CHEBI_6887 <http://purl.obolibrary.org/obo/chebi.owl#CHEBI_6887>"
> this is undesirable since it means we have to do substitution from # -> %23 for the curie to work in another query
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/SciCrunch/NIF-Ontology/issues/18>.
> 

_________________________________________________________________

Jeffrey S. Grethe, Ph.D.                                              email: jgrethe@ncmir.ucsd.edu <mailto:jgrethe@ncmir.ucsd.edu>    
University of California, San Diego
9500 Gilman Drive, M/C 0608
La Jolla, CA 92093-0608

work: (858) 822-0703 (
fax: (858) 246-0644
http://orcid.org/0000-0001-5212-7052 <http://crbs.ucsd.edu/>
http://www.linkedin.com/in/jgrethe <http://www.linkedin.com/in/jgrethe>

This e-mail/fax message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail/fax and destroy all copies of the original message.

**Comment by tgbugs** [comment]
I'v updated the curies file and once bamboo is back up will reload matrix and verify that the problem has been resolved.
