### ISSUE TITLE
Switch from gene to protein

### ISSUE THREAD

**Issue by memartone** [SciCrunch/NIF-Ontology#180]
http://uri.neuinfo.org/nif/nifstd/nlx_cell_100209 is a CUT but it is defined using the Calb2 gene instead of the protein.  We should be consistent with CUTs and use proteins unless it is explicitly stated that they do not express the protein.

**Comment by tgbugs** [comment]
Cuts now use the phenotype indicator when available and will be updated to use the indicator in cases where it is not currently available.
