### ISSUE TITLE
Negative phenotypes did not get entered for Martinotti cell

### ISSUE THREAD

**Issue by memartone** [SciCrunch/NIF-Ontology#203]
In the spreadsheet it says: GABA receptor role,Glutamate Receptor,somatostatin, lacks VIP, lacks PV

but the latter two did not get recorded in the NPO.  Please add and please check whether other negative phenotypes were missed for the CUTs.

**Comment by memartone** [comment]
I don't see that this has been done?

**Comment by tgbugs** [comment]
Fixed now via https://github.com/tgbugs/pyontutils/blob/ee09306ad6d68e5f8e2602ad7054b0f862733d3e/neurondm/neurondm/sheets.py#L441-L443. With visible results https://github.com/SciCrunch/NIF-Ontology/blob/5de3761d0e1bb34344f4215df5e58849fc2569cc/ttl/generated/neurons/cut-release-final.ttl#L377-L384 from the sheet.
