### ISSUE TITLE
Huang LPC neuron should not be a projection neuron. NPOKB:45

### ISSUE THREAD

**Issue by memartone** [SciCrunch/NIF-Ontology#218]
It projects to other layers and areas and so is a long axon interneuron, but it does not project out of cortex as far as I can tell.

**Comment by memartone** [comment]
It is a long range interneuron.  We have examples of those elsewhere.  The definition of an interneuron is that it doesn't project outside of the region (cortex) -it never refers to subregions.  This neuron does not project to the striatum, thalamus, brainstem or spinal cord, correct?

**Comment by memartone** [comment]
You can leave it for now.

**Comment by tgbugs** [comment]
Given that there are many neurons in cortex that do not leave cortex but only project to other cortical areas that are classified as projection neurons, I think that the way that the terminology is used within cortex means that calling an LPC neuron a projection neuron is consistent.

**Comment by tgbugs** [comment]
Resolving as LPC being classified as a projection neuron is correct given further discussion.
