### ISSUE TITLE
Typo in NPOKB:44- GIRA1 and GIRA4 should be GRIA1 and GRIA4

### ISSUE THREAD

**Issue by memartone** [SciCrunch/NIF-Ontology#221]
I cannot find them in any database and they are not in Table S7 but GluA1, GluA4 are in Table 7 and their symbols are Gria1 and Gria4 so I am assuming it is a typo. https://neuinfo.org/data/source/nif-0000-02801-1/search?q=GluA1&l=GluA1

**Comment by tgbugs** [comment]
The Giras are the renames of the genes for the receptor subunits. See https://www.ncbi.nlm.nih.gov/gene/14799 and https://www.ncbi.nlm.nih.gov/gene/14802. From https://github.com/tgbugs/pyontutils/blob/a5e9fcc70d56870e692c17cb7fadce735a281d02/neurondm/neurondm/models/huang2017.py#L156-L157.
