### ISSUE TITLE
marmoset missing from NCBITaxon slim

### ISSUE THREAD

**Issue by tgbugs** [SciCrunch/NIF-Ontology#24]
please add NCBITaxon:9483

**Comment by cmungall** [comment]
It looks like you use your own taxslim. You are welcome to use the 'central' taxslim. The advantage here is that it is regenerated with each NCBITaxon release.

Simply add your ID here
https://github.com/obophenotype/ncbitaxon/blob/master/subsets/taxon-subset-ids.txt
Click edit, add ID, make a pull request

More on NCBITaxon
http://obofoundry.org/ontology/ncbitaxon.html

Slims:
https://github.com/obophenotype/ncbitaxon/blob/master/subsets/README.md

**Comment by tgbugs** [comment]
Yep, had looked into this. I'll submit a pull request it a few days. Thanks!
