### ISSUE TITLE
random pato stuff stored in NIF-GrossAnatomy-Inferred.owl

### ISSUE THREAD

**Issue by tgbugs** [SciCrunch/NIF-Ontology#25]
eg: 
    

```
<owl:Class rdf:about="&PATO;PATO_0002238">
    <rdfs:subClassOf rdf:resource="&PATO;PATO_0000406"/>
</owl:Class>
```

Why is this stuff lurking in here and how did it get there in the first place? Most of these things are in PATO.owl already!

**Comment by cmungall** [comment]
I would recommend not using the bridge file, or NIF-GrossAnatomy

As far as I am aware, NIFGA has not been significantly updated for a number of years. A while ago we agreed to retire NIFGA and replace it with the neuro subset of Uberon (neurolex would be independently coordinated with Uberon). Everything that is in NIFGA is now in Uberon, so there should be no problem with you swapping in uberon (in fact I believe you already have it imported?).

Happy to help in any way

You may also find the [neuro label](https://github.com/obophenotype/uberon/issues?q=is%3Aopen+is%3Aissue+label%3Aneuro) tag on the uberon tracker handy. This section of the ontology is actively used and continually improved.
