### ISSUE TITLE
nlx_158148 -> elephant

### ISSUE THREAD

**Issue by tgbugs** [SciCrunch/NIF-Ontology#26]
We have no ncbitaxon match for elephant, thus we match the resource instead. Probably need to fix this and similar cases (eg emu).

**Comment by cmungall** [comment]
If it helps:

[NCBITaxon:9780](http://purl.obolibrary.org/obo/NCBITaxon_9780) ! Elephantidae   [SYNONYM: "elephants" (exact)]

**Comment by tgbugs** [comment]
There seems to be a bug in scigraph (at least the version I am running) which is preventing 'elephants' from matching as a synonym.

**Comment by tgbugs** [comment]
This is resolved, though scigraph doesn't return values in the order desired (resources first issues). Closing this, will open a scigraph issue about the ranking of results based on category ordering in the yaml file.
