### ISSUE TITLE
DOID:9351 different between production and dev

### ISSUE THREAD

**Issue by tgbugs** [SciCrunch/NIF-Ontology#28]
Something changed for the diabetes entry in DOID, figure out what upstream did.

**Comment by cmungall** [comment]
This is the class for diabetes mellitus -- hopefully this is relatively stable. AFAIK it has not changed in DO

**Comment by tgbugs** [comment]
Looks like this was actually a bug in scigraph. There were no synonyms listed at all but was fixed by rebuilding services and reloading the graph.
