### ISSUE TITLE
Transition to Scicrunch and re-use of NeuroLex terms

### ISSUE THREAD

**Issue by cmaumet** [SciCrunch/NIF-Ontology#31]
Hello,

I was wondering if you could provide us with some inputs on the best practice to re-use a NeuroLex term following transition to SciCrunch?

We are currently using NeuroLex terms as part of the NeuroImaging Data Model (http://nidm.nidash.org). For instance, we use the term "SPM" with the following URI: http://neurolex.org/wiki/nif-0000-00343 (e.g. [example001_spm_results.ttl](https://github.com/incf-nidash/nidm/blob/master/nidm/nidm-results/spm/example001/example001_spm_results.ttl#L119)). But when looking up ["SPM" on SciCrunch](https://scicrunch.org/scicrunch/Resources/record/nlx_144509-1/ba2e10d5-6149-55de-8cad-c72daaa08087/search?q=spm&l=), the main identifier for this term is `SCR_007037` while `nif-0000-00343` is listed as an alternate id. 

So, I was wondering if:
 - you would advice using the main SciCrunch ids (starting with `SCR_`) instead of the original ones (from NeuroLex) in our documents?
 - If the `SCR_` based ids are preferred, then which URL would you recommend for the namespace? I tried: https://scicrunch.org/SCR_007037, https://scicrunch.org/scicrunch/SCR_007037, https://scicrunch.org/scicrunch/SCR_007037, https://scicrunch.org/scicrunch/Resources/SCR_007037, https://scicrunch.org/scicrunch/Resources/record/SCR_007037 but none of these resolved to ["SPM" on SciCrunch](https://scicrunch.org/scicrunch/Resources/record/nlx_144509-1/ba2e10d5-6149-55de-8cad-c72daaa08087/search?q=spm&l=) (while the original http://neurolex.org/wiki/nif-0000-00343 does).

Thank you in advance for your feedback!

**Comment by tgbugs** [comment]
1) Please use the SCR_ identifiers.
2) The prefix that I am planning to use for SCR_ identifiers is `http://scicrunch.org/resolver/` with the curie mapping being `'SCR':'http://scicrunch.org/resolver/SCR_'`. For your example: http://scicrunch.org/resolver/SCR_007037

There will be a full ttl export of the scicrunch registry done weekly that will eventually live [here](http://ontology.neuinfo.org/SciCrunchRegistry/scicrunch-registry.ttl) (currently a broken link). The code to generate it is [here](https://github.com/tgbugs/nlxeol/blob/master/scr_sync.py) though it will not run since the database requires password access.

Let me know if you have other questions. Thanks!

**Comment by yul129** [comment]
Please find below answers to your questions.

  *   you would advice using the main SciCrunch ids (starting with SCR_) instead of the original ones (from NeuroLex) in our documents?

SciCrunch ids will be the ids for both new resources and existing resources and original ids will also been documented as alternative id for existing resources. It is OK to keep the original ids in your documents but for the new entries in the future, there will only be SciCrunch ids.

  *   If the SCR_ based ids are preferred, then which URL would you recommend for the namespace? If the SCR_ based ids are preferred, then which URL would you recommend for the namespace? I tried: <https://scicrunch.org/browse/resources/SCR_007037> https://scicrunch.org/SCR_007037, https://scicrunch.org/scicrunch/SCR_007037, https://scicrunch.org/scicrunch/SCR_007037, https://scicrunch.org/scicrunch/Resources/SCR_007037, https://scicrunch.org/scicrunch/Resources/record/SCR_007037 but none of these resolved to "SPM" on SciCrunch<https://scicrunch.org/scicrunch/Resources/record/nlx_144509-1/ba2e10d5-6149-55de-8cad-c72daaa08087/search?q=spm&l=> (while the original http://neurolex.org/wiki/nif-0000-00343 does).

The URL structure for Scr based ids is https://scicrunch.org/browse/resources/SCR_XXXXXX<https://scicrunch.org/browse/resources/SCR_007037>


________________________________

**Comment by tgbugs** [comment]
Opps broken link. It seems the url structure we want is http://scicrunch.org/browse/resources/SCR_007037. Looks like I will need to update on my end as well. However, I might still suggest the resolver since that will not change even if we fiddle with our urls in the future. Do we have a wiki/docs for this lurking somewhere? I will get a better answer asap.

**Comment by jgrethe** [comment]
Yueling - Tom responded already.

Cheers,
Jeff

> On Feb 2, 2016, at 9:54 AM, yul129 <notifications@github.com> wrote:
> 
> Please find below answers to your questions.
> 
> * you would advice using the main SciCrunch ids (starting with SCR_) instead of the original ones (from NeuroLex) in our documents?
> 
> SciCrunch ids will be the ids for both new resources and existing resources and original ids will also been documented as alternative id for existing resources. It is OK to keep the original ids in your documents but for the new entries in the future, there will only be SciCrunch ids.
> 
> * If the SCR_ based ids are preferred, then which URL would you recommend for the namespace? If the SCR_ based ids are preferred, then which URL would you recommend for the namespace? I tried: <https://scicrunch.org/browse/resources/SCR_007037> https://scicrunch.org/SCR_007037, https://scicrunch.org/scicrunch/SCR_007037, https://scicrunch.org/scicrunch/SCR_007037, https://scicrunch.org/scicrunch/Resources/SCR_007037, https://scicrunch.org/scicrunch/Resources/record/SCR_007037 but none of these resolved to "SPM" on SciCrunch<https://scicrunch.org/scicrunch/Resources/record/nlx_144509-1/ba2e10d5-6149-55de-8cad-c72daaa08087/search?q=spm&l=> (while the original http://neurolex.org/wiki/nif-0000-00343 does).
> 
> The URL structure for Scr based ids is https://scicrunch.org/browse/resources/SCR_XXXXXX<https://scicrunch.org/browse/resources/SCR_007037>
> 
> 
> ________________________________
> From: Camille Maumet [notifications@github.com]
> Sent: Tuesday, February 02, 2016 8:30 AM
> To: SciCrunch/NIF-Ontology
> Subject: [NIF-Ontology] Transition to Scicrunch and re-use of NeuroLex terms (#31)
> 
> 
> Hello,
> 
> I was wondering if you could provide us with some inputs on the best practice to re-use a NeuroLex term following transition to SciCrunch?
> 
> We are currently using NeuroLex terms as part of the NeuroImaging Data Model (http://nidm.nidash.org). For instance, we use the term "SPM" with the following URI: http://neurolex.org/wiki/nif-0000-00343 (e.g. example001_spm_results.ttl<https://github.com/incf-nidash/nidm/blob/master/nidm/nidm-results/spm/example001/example001_spm_results.ttl#L119>). But when looking up "SPM" on SciCrunch<https://scicrunch.org/scicrunch/Resources/record/nlx_144509-1/ba2e10d5-6149-55de-8cad-c72daaa08087/search?q=spm&l=>, the main identifier for this term is SCR_007037 while nif-0000-00343 is listed as an alternate id.
> 
> So, I was wondering if:
> 
> * you would advice using the main SciCrunch ids (starting with SCR_) instead of the original ones (from NeuroLex) in our documents?
> * If the SCR_ based ids are preferred, then which URL would you recommend for the namespace? I tried: https://scicrunch.org/SCR_007037, https://scicrunch.org/scicrunch/SCR_007037, https://scicrunch.org/scicrunch/SCR_007037, https://scicrunch.org/scicrunch/Resources/SCR_007037, https://scicrunch.org/scicrunch/Resources/record/SCR_007037 but none of these resolved to "SPM" on SciCrunch<https://scicrunch.org/scicrunch/Resources/record/nlx_144509-1/ba2e10d5-6149-55de-8cad-c72daaa08087/search?q=spm&l=> (while the original http://neurolex.org/wiki/nif-0000-00343 does).
> 
> Thank you in advance for your feedback!
> 
> —
> Reply to this email directly or view it on GitHub<https://github.com/SciCrunch/NIF-Ontology/issues/31>.
> —
> Reply to this email directly or view it on GitHub <https://github.com/SciCrunch/NIF-Ontology/issues/31#issuecomment-178718051>.
> 




_________________________________________________________________

Jeffrey S. Grethe, Ph.D.                                              email: jgrethe@ncmir.ucsd.edu <mailto:jgrethe@ncmir.ucsd.edu>    
University of California, San Diego
9500 Gilman Drive, M/C 0608
La Jolla, CA 92093-0608

work: (858) 822-0703 (
fax: (858) 246-0644
http://orcid.org/0000-0001-5212-7052 <http://crbs.ucsd.edu/>
http://www.linkedin.com/in/jgrethe <http://www.linkedin.com/in/jgrethe>

This e-mail/fax message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail/fax and destroy all copies of the original message.

**Comment by jgrethe** [comment]
Hi Tom,
Shouldn’t be browse-resources… Should be a resolver address - as that can be fixed.  NeuroLex had the uri.neuinfo.org/ID format.  We can do something similar for SciCrunch and InterLex.

> On Feb 2, 2016, at 10:01 AM, Tom Gillespie <notifications@github.com> wrote:
> 
> Opps broken link. It seems the url structure we want is http://scicrunch.org/browse/resources/SCR_007037 <http://scicrunch.org/browse/resources/SCR_007037>. Looks like I will need to update on my end as well. However, I might still suggest the resolver since that will not change even if we fiddle with our urls in the future. Do we have a wiki/docs for this lurking somewhere? I will get a better answer asap.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/SciCrunch/NIF-Ontology/issues/31#issuecomment-178723454>.
> 

_________________________________________________________________

Jeffrey S. Grethe, Ph.D.                                              email: jgrethe@ncmir.ucsd.edu <mailto:jgrethe@ncmir.ucsd.edu>    
University of California, San Diego
9500 Gilman Drive, M/C 0608
La Jolla, CA 92093-0608

work: (858) 822-0703 (
fax: (858) 246-0644
http://orcid.org/0000-0001-5212-7052 <http://crbs.ucsd.edu/>
http://www.linkedin.com/in/jgrethe <http://www.linkedin.com/in/jgrethe>

This e-mail/fax message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail/fax and destroy all copies of the original message.

**Comment by cmaumet** [comment]
Thank you very much for your replies! 

So, just to confirm, the URIs for SciCrunch terms will have the following form: `http://scicrunch.org/resolver/SCR_***` ?

I know this is work-in-progress but could you confirm that ultimately the `SCR_ ***` ids will be available for all NeuroLex terms (including the ones that were not part of the Resource Identification Initiative)? E.g. we are planning to re-use [nlx:nlx_inv_090912 ("Magnetic resonance imaging")](http://neurolex.org/wiki/nlx_inv_090912). If so, and if there is a place were I could look up the `SRC_***` that have already been assigned. Please let me know! 

The terms we are interested in are:
 - [nlx:nlx_inv_090912 ("Magnetic resonance imaging")](http://neurolex.org/wiki/nlx_inv_090912)
 -

**Comment by tgbugs** [comment]
Yes `http://scicrunch.org/resolver/SCR_***` is preferred. We want to provide a `http://resolver.scicrunch.org/SCR_***` in the future but links with that structure will 404 at the moment.

For other neurolex terms please use `http://uri.neuinfo.org/nif/nifstd/` as your iri prefix (namespace). As we start moving terms out of neurolex and into nifstd that resolver will be updated so that it redirects to the most recent version of the term.

**Comment by satra** [comment]
@tgbugs and @jgrethe - would it be possible to introduce a sameAs property for any of the scicrunch or interlex terms that are taking over the older neurolex terms?

this would at least help resolve things given the older IRIs will go away. on our side we can try to add information to indicate that queries should take sameAs into account.

**Comment by jgrethe** [comment]
Yes.  We have done that for the public resolver for resources and these could be incorporated into the ontology as well. 

Cheers,
Jeff

> On Feb 3, 2016, at 5:24 AM, Satrajit Ghosh <notifications@github.com> wrote:
> 
> @tgbugs <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tgbugs&d=CwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=VoBnXVyFWlbGZNrES22a2h0PqI4m1kGEUyTwLwBBYIQ&m=yGFbOjBBfz6T3rHBIMFZPY9dRkpcYefuCkSqDQNtJPQ&s=AEJCWv1sMJ4JYfCmWysDTZa3pLDxWAqJiY6y4WO76MU&e=> and @jgrethe <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jgrethe&d=CwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=VoBnXVyFWlbGZNrES22a2h0PqI4m1kGEUyTwLwBBYIQ&m=yGFbOjBBfz6T3rHBIMFZPY9dRkpcYefuCkSqDQNtJPQ&s=zvSktdG3cJ_krM4JIfDbk_3SQrjImuorSOqLXKUlKXU&e=> - would it be possible to introduce a sameAs property for any of the scicrunch or interlex terms that are taking over the older neurolex terms?
> 
> this would at least help resolve things given the older IRIs will go away. on our side we can try to add information to indicate that queries should take sameAs into account.
> 
> —
> Reply to this email directly or view it on GitHub <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_SciCrunch_NIF-2DOntology_issues_31-23issuecomment-2D179226979&d=CwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=VoBnXVyFWlbGZNrES22a2h0PqI4m1kGEUyTwLwBBYIQ&m=yGFbOjBBfz6T3rHBIMFZPY9dRkpcYefuCkSqDQNtJPQ&s=Q78eLQWNaqr2BXz9cHFrCUR87BVJLlWcCR3mQLw8uq8&e=>.
> 

_________________________________________________________________

Jeffrey S. Grethe, Ph.D.                                              email: jgrethe@ncmir.ucsd.edu <mailto:jgrethe@ncmir.ucsd.edu>    
University of California, San Diego
9500 Gilman Drive, M/C 0608
La Jolla, CA 92093-0608

work: (858) 822-0703 (
fax: (858) 246-0644
http://orcid.org/0000-0001-5212-7052 <http://crbs.ucsd.edu/>
http://www.linkedin.com/in/jgrethe <http://www.linkedin.com/in/jgrethe>

This e-mail/fax message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail/fax and destroy all copies of the original message.

**Comment by tgbugs** [comment]
@satra I will include some form of a sameAs property in my export of the resource registry as well. I am currently exporting it as an an annotation property but could easily change it to an object property if that would make your life easier.

**Comment by cmaumet** [comment]
Thank you for your feedback! From now on, we will use the `http://scicrunch.org/resolver/` and `http://uri.neuinfo.org/nif/nifstd/` namespaces as suggested, this update is implemented in https://github.com/incf-nidash/nidm/pull/374.

I have open #34 to discuss more specific term re-use. I think that the discussions can continue over there and that we can close this issue.

**Comment by tgbugs** [comment]
Will close after I add a wiki page that covers this.

**Comment by tgbugs** [comment]
https://github.com/SciCrunch/NIF-Ontology/wiki/Identifiers-for-existing-terms
https://github.com/SciCrunch/NIF-Ontology/wiki/Identifiers-for-research-resources
https://github.com/SciCrunch/NIF-Ontology/wiki/Identifiers-for-new-terms
