### ISSUE TITLE
diabetes mellitus synonyms

### ISSUE THREAD

**Issue by koweilin** [SciCrunch/NIF-Ontology#44]
We have some dkNET users trying to search "type 2 diabetes mellitus" or "type 1 diabetes mellitus" relevant funding opportunities.

When users typed in type 2 diabet.. in the search bar, the system will suggest them  "type 2 diabetes mellitus". Therefore most users will go to select "type 2 diabetes mellitus" (or "type 1 diabetes mellitus" if they typed in "type 1 diabete....").

The problem is by clicking funding or filtering funding opportunities, it shows 0 results under dkNET.org [https://dknet.org/Funding/search?q=%22type%201%20diabetes%20mellitus%22&l=type%201%20diabetes%20mellitus](url)
[https://dknet.org/Funding/search?q=%22type%202%20diabetes%20mellitus%22&l=type%202%20diabetes%20mellitus](url)

I found there is no synonyms such as type 2 diabetes for type 2 diabetes mellitus in our system. Is it the problem causing "0" results? Are we using any standard synonyms for medical diseases in the system?

**Comment by tgbugs** [comment]
So the issue is that
http://nif-services.neuinfo.org/servicesv1/v1/query?q=type%201%20diabetes%20mellitus
and
http://nif-services.neuinfo.org/servicesv1/v1/query?q=type%202%20diabetes%20mellitus
are going to continue to return those expansions until we get ontoquest ripped out and replaced with scigraph. I'm going to talk to @wawong about progress on that front on Monday.

On the ontology side, those terms come from DOID, so what I will do is create a DOID bridge and add synonyms "type 1 diabetes" to DOID:9744 and "type 2 diabetes" to DOID:9352 which come back with 181, and 94 results respectively. However, until we get ontoquest replaced those changes won't show up in search.

**Comment by koweilin** [comment]
Synonyms for type 1 diabetes mellitus:

Type 1 diabetes
Diabetes, type 1
Diabetes, type I
Type 1 diabetes mellitus
Type I diabetes mellitus
Diabetes mellitus type 1
Diabetes mellitus, type 1
Diabetes mellitus type I
Diabetes mellitus, type I
Juvenile diabetes
Juvenile-onset diabetes
Insulin-dependent diabetes
Insulin dependent diabetes
Insulin-dependent diabetes mellitus
Insulin dependent diabetes mellitus
Insulin-dependent diabetes mellitus 1
Insulin-dependent diabetes mellitus I 
Diabetes mellitus insulin-dependent
Diabetes mellitus, insulin-dependent
Diabetes Mellitus, Insulin-Dependent, 1
Diabetes Mellitus, Insulin-Dependent, I 
IDDM .......(*Acronym from Insulin-dependent diabetes mellitus)

**Comment by koweilin** [comment]
Synonyms for Type 2 diabetes mellitus:

Type II diabetes mellitus
T2DM
Type 2 diabetes
Type II diabetes
Diabetes, type 2
Diabetes, type II 
Diabetes mellitus type 2
Diabetes mellitus type II
Diabetes mellitus, type 2
Diabetes mellitus, type II
Noninsulin-dependent diabetes
Noninsulin-dependent diabetes mellitus
Noninsulin dependent diabetes
Noninsulin dependent diabetes mellitus
Non insulin dependent diabetes
Non insulin dependent diabetes mellitus
Non-insulin dependent diabetes
Non-insulin dependent diabetes mellitus
Non-insulin-dependent diabetes
Non-insulin-dependent diabetes mellitus
NIDDM
Diabetes mellitus, non insulin dependent
Diabetes mellitus, non-insulin dependent
Diabetes mellitus, non-insulin-dependent
Type 2 diabetes mellitus non-insulin dependent
Type II diabetes mellitus non-insulin dependent
Type 2 diabetes mellitus, noninsulin dependent
Type II diabetes mellitus, noninsulin dependent
Type 2 diabetes mellitus non-insulin-dependent
Type II diabetes mellitus non-insulin-dependent
Type 2 diabetes mellitus non insulin dependent
Type II diabetes mellitus non insulin dependent
Adult onset diabetes
Adult onset diabetes mellitus
Adult-onset diabetes
Adult-onset diabetes mellitus
Diabetes mellitus, adult onset
Diabetes mellitus, adult-onset
