### ISSUE TITLE
Update description of the International Geo Sample Number (IGSN)

### ISSUE THREAD

**Issue by jklump** [SciCrunch/NIF-Ontology#50]
The information about the syntax of the International Geo Sample Number (IGSN) is out of date. The homepage of the IGSN Implementing Organisation is now at http://www.igsn.org, the technical documentation can be found at http://igsn.github.io, the syntax is described at http://igsn.github.io/syntax.

**Comment by jgrethe** [comment]
Yueling: This looks like a registry record that needs updating...

**Comment by yul129** [comment]
This is not a registered resource.

**Comment by tgbugs** [comment]
I looked around the ontology and could only find two references to the IGSN in the ontology
http://scicrunch.org/resolver/SCR_002213 and http://scicrunch.org/resolver/SCR_002222. @jklump do you have a link to the out of date information? Thanks!

**Comment by jklump** [comment]
Thanks for following up on this. I found the reference in http://neurolex.org/wiki/Category:International_Geo_Sample_Number. This might have changed in the transition process of Neurolex to a successor system.

**Comment by KEJensen** [comment]
IGSN has been curated and should appear on the public database on Monday, July 4. The citation to use is as follows: International Geo Sample Number, RRID:SCR_014505.
