### ISSUE TITLE
End stage renal disease synonyms

### ISSUE THREAD

**Issue by koweilin** [SciCrunch/NIF-Ontology#51]
Here are the synonyms for end stage renal disease:

Kidney disease, end-stage
Kidney disease, end stage
Renal disease, end-stage
Renal disease, end stage
End-Stage Renal Disease
ESRD
End-stage kidney disease
End stage kidney disease
Renal failure, end stage
Renal failure, end-stage
End-stage renal failure
End stage renal failure
ESRF
End-stage kidney failure
End stage kidney failure
End stage chronic renal failure
ESCRF
Chronic kidney disease, stage 5

**Comment by tgbugs** [comment]
DOID:783
