### ISSUE TITLE
transition iris to http://uri.neuinfo.org/nif/nifstd/

### ISSUE THREAD

**Issue by tgbugs** [SciCrunch/NIF-Ontology#59]
In order for this to happen we probably need to be able to point the resolver at scigraph or to interlex?
@jgrethe thoughts?

uniqueness issues related to flattening:
https://github.com/twhetzel/nifstd-qa/blob/master/QA-UniqueTermIds/data_files/TermsForReview.txt

**Comment by jgrethe** [comment]
Was this an old JIRA ticket?  If so - wouldn't we be pointing at InterLex?

**Comment by tgbugs** [comment]
It was an old jira ticket, I would prefer to move everything over to interlex. @cmungall has been using the uri.neuinfo.org for some of the neurolex terms, but I think if we are going to transition off the ontology.neuinfo.org, we should transition to interlex so we can focus our efforts there (regardless I will build a big list of old -> new iri mappings).

**Comment by cmungall** [comment]
In uberon we use the prefix uri.neuinfo.org as the base regardless of whether the suffix originated in NIFSTD or in Neurolex (there were a few clashes, which I documented a while ago, not sure if these were every fixed).

Happy to switch the prefix, but it would be good to have some idea of plans for interlex to be sure these would be rewired to the correct URL, to avoid some of the issues in the original nifstd->neurolex transition.

**Comment by satra** [comment]
@tgbugs, @jgrethe - any updates on where we should point to for the new neurolex?

**Comment by tgbugs** [comment]
@satra @jgrethe Hi Satra, for the resolver you should point to http://uri.neuinfo.org/nif/nifstd/. I am in the process of converting all the existing ontology URIs to work from that endpoint, however it will still be a bit. Otherwise we are planning to have a 'neurolex' landing page as part of interlex which I think we are planning to show at neuroinformatics. Jeff will have a better idea about that though.

**Comment by tgbugs** [comment]
Implementation for redirecting old URIs is here https://github.com/tgbugs/pyontutils/tree/master/resolver.
