### ISSUE TITLE
Worm isn't a synonym for C elegans?

### ISSUE THREAD

**Issue by jal157** [SciCrunch/NIF-Ontology#6]
I searched NIF for worm, and it doesn’t appear to be a synonym for C elegans. I thought we took care of that a long time ago?

Maryann Martone, Ph. D.
Professor-in-Residence
Department of Neuroscience
University of California, San Diego
San Diego, CA 92093-0608

858-822-0745

**Comment by tgbugs** [comment]
NIFORG:birnlex_420 is indeed missing worm as a synonym

**Comment by tgbugs** [comment]
NCBITaxon:6239
