### ISSUE TITLE
Obsolete brain of rodent

### ISSUE THREAD

**Issue by memartone** [SciCrunch/NIF-Ontology#67]
In Knowledge Space, we have the class "Obsolete brain of rodent" from UBERON:  UBERON:0023939.  I'm assuming this is an obsolete class.  We should probably have a boneyard for obsolete classes along with a note as to why the classes were or were not deprecated.

**Comment by jgrethe** [comment]
It should be a hidden bone yard as users may not understand the ways of ontology maintenance

**Comment by tgbugs** [comment]
closing as duplicate of KS issues #51
