### ISSUE TITLE
Offline Message from Maryann Martone: I think we have to do a serious review ...

### ISSUE THREAD

**Issue by SciCrunch-Synapse** [SciCrunch/NIF-Ontology#68]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#11914](https://scicrunch.zendesk.com/agent/tickets/11914)
**Priority:** N/A
**Group:** Support
**Requester:** mmartone@ucsd.edu
**Organization:** N/A
**Assignee:** N/A

**Original ticket description:**

<blockquote><div class="zd-comment">
<p dir="auto">From: Maryann Martone &lt;<a href="mailto:mmartone@ucsd.edu" rel="noreferrer">mmartone@ucsd.edu</a>&gt;
<br>Phone: 
<br>URL: <a href="https://neuinfo.org/data/search?q=Matlab_software&amp;l=%22Matlab_software%22" rel="nofollow noreferrer" target="_blank">https://neuinfo.org/data/search?q=Matlab_software&amp;l=%22Matlab_software%22</a></p>

<p dir="auto">I think we have to do a serious review of NEMO in SciGraph.  It is causing some problems in search, e.g., "Matlab software" doesn't return any results.</p>

<p dir="auto">----
<br>Zopim
<br><a href="https://www.zopim.com" rel="nofollow noreferrer" target="_blank">https://www.zopim.com</a></p>
</div></blockquote>

**Comment by SciCrunch-Synapse** [comment]
*Comment made from Zendesk by SciCrunch on 2016-08-08 at 17:49:*

<blockquote><div class="zd-comment"><p dir="auto">Have transitioned ticket to GitHub: 
<br><a href="https://github.com/SciCrunch/NIF-Ontology/issues/68" rel="nofollow noreferrer" target="_blank">https://github.com/SciCrunch/NIF-Ontology/issues/68</a></p></div></blockquote>

**Comment by tgbugs** [comment]
@KEJensen can you please add 'MATLAB software' as a synonym for SCR:001622

**Comment by tgbugs** [comment]
Import addressed by 8cee9a0a377e1a85d622ad98f312f16742325b78, but still need to clean up some dangling identifiers.

**Comment by tgbugs** [comment]
closed by d09d783e930e7cf5da109d79defb8e44dddcf3f0
