### ISSUE TITLE
NIF-GO-CC-Bridge.ttl causes most unsatisfiable axioms

### ISSUE THREAD

**Issue by tgbugs** [SciCrunch/NIF-Ontology#69]
GO:0043005, sao-20931889, sao-867568886 unsatisfiable
GO:0043005 asserts equivalence to both of these classes despite the fact that they are disjoint.
Should `Neuron Process` be disjoint from `Neuron Protrusion`? I think the answer is yes, and that GO:0043005 is incorrect.

**Comment by tgbugs** [comment]
Related
GO:0043198, Trunk, `Dendritic Shaft` caused by conflict centring on `Subregional Part Of Neuron Process`

**Comment by cmungall** [comment]
Is the plan to maintain the bridge and a distinct SAO moving forward? 

The plan we put into place here: http://www.jbiomedsem.com/content/4/1/20

has us using GO CC as the standard, no need to maintain mappings

**Comment by tgbugs** [comment]
Not entirely sure what to do.
I suspect that I can resolve most of these by removing one of the equivalentClass axioms* from the bridge and replacing it with another edge 'alsoSubsumesSAO' or something similar. However I expect that this will cause nasty issues where synonyms in GO are considered as disjoint entities in NIF. Thoughts?

* It seems that most of the issues arise directly from equivalentClass assertions in the bridge being made between two disjoint classes (first comment), or cases where a an equivalentClass axiom conflicts indirectly because SAO has disjointness axioms between parts and subparts (second comment).

**Comment by tgbugs** [comment]
closed by 3353b34034581c42ae729805a531d641b9585334

The solution was to remove spurious equivalentClass assertions where GO had has_related_synonym and to make the other GO terms equivalentClasses of unions of the disjoint nif terms as they always should have been.
