### ISSUE TITLE
missues of deprecation

### ISSUE THREAD

**Issue by tgbugs** [SciCrunch/NIF-Ontology#78]
[CHEBI:35341](https://github.com/SciCrunch/NIF-Ontology/blob/d379d13371f1051942936a4d7030941881634035/ttl/NIF-Chemical.ttl#L2955) for example deprecates an id that is still in active use in the parent ontology. I'm sure there are more examples of this. This probably comes from the fact that externally sourced identifiers were treated as if they were internal identifiers.

**Comment by cmungall** [comment]
is this a problem with CHEBI or somthing specific to your pipeline? Let me know if I can help with former

**Comment by tgbugs** [comment]
This is a problem within our pipeline.

**Comment by tgbugs** [comment]
This specific issue has been resolved as of 8efd77996fa2047749b7d1181dcc31df50f84522.
