### ISSUE TITLE
generate alternate/deprecated iris file

### ISSUE THREAD

**Issue by tgbugs** [SciCrunch/NIF-Ontology#82]
We need a generated file that keeps a list of deprecated iris, no labels, with `oboInOwl:replacedBy` pointing to the 'live' class for the purposes of resolution.

**Comment by cmungall** [comment]
Ironically, oboInOwl:replacedBy is itself replaced by obo:IAO_0100001

This should really be there in the oio ontology file, but for now it is recorded as part of the OBO standard:

http://owlcollab.github.io/oboformat/doc/obo-syntax.html#5.8

**Comment by tgbugs** [comment]
Ah, good to know. Thanks!

**Comment by tgbugs** [comment]
Completed by https://github.com/tgbugs/pyontutils/blob/master/pyontutils/necromancy.py. Changes to deprecation practices in newer versions of external ontologies have improved the situation here as well.
