### ISSUE TITLE
Ionic currents

### ISSUE THREAD

**Issue by christian-oreilly** [SciCrunch/NIF-Ontology#91]
NIF coverage of ionic currents is rather partial. I've created a page where I describe my attempts at improving this coverage: https://github.com/BlueBrain/nat/wiki/Ontology-terms-for-ionic-currents

Any chance these can be integrated in NIF?

**Comment by tgbugs** [comment]
Yes! We would love to get these in. I think we need to get the currents in by themselves independent of their channels. We will need to think a bit about where currents fit in the larger hierarchy.
If you could create a little owl file (serialized in ttl preferably) with the outline of the hierarchy that you have I can match them up with existing terms. Then once we figure out exactly where to put the currents in the hierarchy we can get them identifiers in interlex (https://scicrunch.org/create/term) and integrate them fully. Does that sound reasonable?

PS I think there is an opportunity to rethink how we are modelling ion channels and are not alone in the need. See for example https://github.com/SciCrunch/NIF-Ontology/issues/80. `NIFMOL:nifext_2500` and `NIFMOL:nifext_2502` seems to be where most things start currently but those conflate the proteins with the currents.

**Comment by christian-oreilly** [comment]
Hi Tom,

Sounds reasonable. However, I think what you are asking for (except the
fact that it should be formatted in owl/ttl) is already described at the
link I provided (
https://github.com/BlueBrain/nat/wiki/Ontology-terms-for-ionic-currents).
There are three parts to this page:

1 - A hierarchy (in form of a bullet point list with varying depth)
2 - A list of terms from the hierarchy in 1  that are already available in
NIF (ids and labels provided)
2 - A list of the terms to add to NIF to have the full hierarchy described
in 1

Note 1: The full hierarchy described in 1 has only one top parent term:
NIFMOL:nifext_8054 -- Transmembrane ionic current. Consequently, every new
term has a lineage to an already existing NIF term.

I tried the page https://scicrunch.org/create/term to see how it can be
used to add new terms. However, it didn't showed me any form where I could
enter new terms...


[image: Images intégrées 1]

Concerning your PS: Yes, I think that we must clearly distinguish ionic
currents and ionic channels. Obviously, these can come to converge to the
functional and structural parts of a same entity in case where the
knowledge has been refined enough to talk about the current of a specific
ionic channel type, but most ionic currents (e.g., all the currents
described in the page I linked to) are the results of the interaction of an
unknown mixture of various ion channel types.

By the way, I plan to attend your next meeting call with Silvia on Tuesday
so that I can introduce myself to you more adequately and that we can
discuss any issues related to the present topic.

Best,

Christian




2017-02-15 20:49 GMT+01:00 Tom Gillespie <notifications@github.com>:

**Comment by tgbugs** [comment]
@christian-oreilly 
I have created a new branch for reviewing the new terms that we want to include. The temporary file with the new classes is [here](https://github.com/SciCrunch/NIF-Ontology/blob/ionic-currents/ttl/TEMPcurrents.ttl). Take a look make sure everything seems ok, I will get real ILX ids for them and move them into NIF-Molecule.ttl.

This is the generated hierarchy from the terms I have added (in the separate file for review).
```
Transmembrane ionic current
├──Excitatory postsynaptic current
├──Inhibitory postsynaptic current
├──Leak ionic current
├──Chloride current
│  ├──Calcium activated chloride current
│  └──GABA related chloride current
├──Non-selective current
│  ├──Calcium activated nonspecific cation current
│  └──Cyclic nucleotide gated nonspecific cation current
│     └──Inward rectifier current
├──Calcium current
│  ├──Low threshold calcium T current
│  ├──N type calcium current
│  ├──Slow high threshold calcium current
│  └──q and p type calcium current
├──Sodium current
│  ├──Sodium leak current
│  ├──Sodium persistent current
│  ├──Sodium transient fast current
│  └──Sodium transient slow current
└──Potassium current
   ├──Fast voltage gated potassium current
   ├──M type potassium current
   ├──Potassium delayed rectifier
   ├──Potassium inward rectifier current
   ├──Potassium leak current
   ├──A current
   │  └──I A, slow
   └──Calcium-dependent potassium current
      ├──Fast voltage and calcium dependent potassium current
      ├──Medium calcium dependent AHP potassium current
      └──Slow calcium dependent AHP potassium current
```

**Comment by christian-oreilly** [comment]
Looks all good to me. I just made a small modification (adding a synonym) which I committed.

**Comment by tgbugs** [comment]
@christian-oreilly these are up on matrix http://matrix.neuinfo.org:9000/scigraph/vocabulary/id/ILX:0115055. I sent you a csv with the identifier mappings, but I am including them here as well for the record.

```BBP_nlx_0001 ('BBP_nlx_0001', 'ILXREPLACE:e55f7119387b94bdaf2d9b9d9f1d1a82', 'ILX:0115045')
BBP_nlx_0002 ('BBP_nlx_0002', 'ILXREPLACE:3711531e7a6a4c36be36402799879855', 'ILX:0115055')
BBP_nlx_0003 ('BBP_nlx_0003', 'ILXREPLACE:719fdb67ef87beb098f1a71afb0722c0', 'ILX:0115057')
BBP_nlx_0004 ('BBP_nlx_0004', 'ILXREPLACE:8d046788739d6a5a2811237140901836', 'ILX:0115058')
BBP_nlx_0005 ('BBP_nlx_0005', 'ILXREPLACE:5a672be9a77dfdb8f3e7de7e985503af', 'ILX:0115056')
BBP_nlx_0006 ('BBP_nlx_0006', 'ILXREPLACE:b1518541c88de516c479eb374056a3a8', 'ILX:0115050')
BBP_nlx_0007 ('BBP_nlx_0007', 'ILXREPLACE:6a4edad09d025f6847714281b9dead85', 'ILX:0115052')
BBP_nlx_0008 ('BBP_nlx_0008', 'ILXREPLACE:8abd46a40a9a69d89f08e19449ae54ba', 'ILX:0115047')
BBP_nlx_0009 ('BBP_nlx_0009', 'ILXREPLACE:68b35d60cbaf4fc37a6acbcf776b3f2e', 'ILX:0115042')
BBP_nlx_0010 ('BBP_nlx_0010', 'ILXREPLACE:e864beaa642bb23a5e6e2148d59c086f', 'ILX:0115053')
BBP_nlx_0011 ('BBP_nlx_0011', 'ILXREPLACE:a892e32626211ac51c29f6399401aef0', 'ILX:0115046')
BBP_nlx_0012 ('BBP_nlx_0012', 'ILXREPLACE:70bce66b82c7959019cde2aba9f6f603', 'ILX:0115054')
BBP_nlx_0013 ('BBP_nlx_0013', 'ILXREPLACE:6e663e7389d8edec8c569982c543ae9a', 'ILX:0115059')
BBP_nlx_0014 ('BBP_nlx_0014', 'ILXREPLACE:1d77d7b0ef0fedac25dfbc8f718b3e9a', 'ILX:0115049')
BBP_nlx_0015 ('BBP_nlx_0015', 'ILXREPLACE:cbf5f2f87cd34c2b6b3873e65ac82162', 'ILX:0115038')
BBP_nlx_0016 ('BBP_nlx_0016', 'ILXREPLACE:6e3b7910f481bd23246f8629f63bdc6c', 'ILX:0115039')
BBP_nlx_0017 ('BBP_nlx_0017', 'ILXREPLACE:a299cacbf838c74b0aba21c0815908f4', 'ILX:0115040')
BBP_nlx_0018 ('BBP_nlx_0018', 'ILXREPLACE:31378bc0c7fed58a442bb103027da8d3', 'ILX:0115041')
BBP_nlx_0019 ('BBP_nlx_0019', 'ILXREPLACE:27ccaf8f5806dca155f841d0f3994288', 'ILX:0115051')
BBP_nlx_0020 ('BBP_nlx_0020', 'ILXREPLACE:8ff86d336ef8ddc4c8dbe851ada48c18', 'ILX:0115043')
BBP_nlx_0024 ('BBP_nlx_0024', 'ILXREPLACE:1f0a682fee89bca90442e339f38909f5', 'ILX:0115048')
BBP_nlx_0027 ('BBP_nlx_0027', 'ILXREPLACE:b1c7dbf2c7ba9cf1b64d6c57f880eec6', 'ILX:0115044')
```
