### ISSUE TITLE
chebislim conflicts with NIF-Chemical modelling

### ISSUE THREAD

**Issue by tgbugs** [SciCrunch/NIF-Ontology#95]
Now that we are importing the modelling that chebi uses directly we have encountered an issue because sex hormone and steroid hormone now conflict because we internally assigned sex hormone as a subclass of Hormone which is a role, and thus directly conflicts with the fact that chebi does not model it that way. Not entirely sure the best way to resolve this.

**Comment by cmungall** [comment]
NSWYM:

```
 / CHEBI:50906 ! role
  is_a CHEBI:24432 ! biological role
   is_a CHEBI:33280 ! molecular messenger
    is_a CHEBI:24621 ! hormone
     is_a CHEBI:50112 ! sex hormone *** 
```

in GO we make a shadow hierarchy: 'chemical substance with X role', effectively conflating isa and has-role, not sure if that helps

**Comment by tgbugs** [comment]
Sorry, I was not clear about how this conflict was arising. The issue comes from the fact that in one place in [NIF-Chemical](https://github.com/SciCrunch/NIF-Ontology/blob/nif3/ttl/NIF-Chemical.ttl#L2071) we have
```
CHEBI:50113 ! androgen 
is_a CHEBI:26764 ! steroid hormone
```
and in another (chebislim.ttl)
```
CHEBI:50113 ! androgen
is_a CHEBI:50112 ! sex hormone
```
Based on this I think that the entry in NIF-Chemical is simply incorrect. And indeed, removing that axiom solves the problem. The conflict arises from the fact that steroid hormone and sex hormone are not compatible subClassOf which is correct, but somehow we got steroid hormone in the hierarchy.

**Comment by tgbugs** [comment]
212b707b8ef0d51cf58ba963f5751413cf8c26c9 closes this.
